In [ ]:
#ARRAY CREATION

In [ ]:
#1.	Initialize an empty array with size 2X2.
#import the NumPy
import numpy as np
#initialize an empty array with size 2x2
empty_array = np.empty((2, 2)) #creates an uninitialized array
print("Empty Array:\n", empty_array)

Empty Array:
 [[4.65930425e-310 0.00000000e+000]
 [6.67325236e-310 4.65829977e-310]]


In [ ]:
#2.	Initialize an all one array with size 4X2.
#import the Numpy
import numpy as np
#initialize an all-one array with size 4x2
ones_array = np.ones((4, 2)) #creates an array filled with  ones
print("All-Ones Array:\n", ones_array)

All-Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#3.	Return a new array of given shape and type, filled with fill value.
#import the Numpy
import numpy as np
#return a new array filled with a specific value
filled_array = np.full((3, 3), 7)#creates a 3x3 array filled with 7
print("Array filled with 7:\n", filled_array)

Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#4.	Return a new array of zeros with same shape and type as a given array.
#import NumPy
import numpy as np
#return a new array with the same shape as a given array
reference_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(reference_array)#zeros matching reference array's shape
print("Zero-like Array:\n", zeros_like_array)

Zero-like Array:
 [[0 0]
 [0 0]]


In [ ]:
#5.	Return a new array of ones with same shape and type as a given array
#import NumPy
import numpy as np
#return a new ones array with the same shape as a given array
ones_like_array = np.ones_like(reference_array)#ones matching reference array's shape
print("Ones_Like Array:\n", ones_like_array)


Ones_Like Array:
 [[1 1]
 [1 1]]


In [ ]:
#6.	For an existing list new_list = [1,2,3,4] convert to an numpy array.
#import NumPY
import numpy as np
#convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)#coverts list to NumPy array
print("Converted NumPy Array:\n", numpy_array)

Converted NumPy Array:
 [1 2 3 4]


In [ ]:
#Array Manipulation: Numerical Ranges and Array indexing


In [ ]:
#1.	Create an array with values ranging from 10 to 49
#import NumPy
import numpy as np
#create an array with values from 10 to 49
#using arrange() to generate numbers in a specific range
range_array = np.arange(10, 50)
print("Range Array:\n", range_array)

Range Array:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Import NumPy
import numpy as np

# Task: Create a 3x3 matrix with values ranging from 0 to 8
# Generate a sequence of numbers from 0 to 8
# Reshape the sequence into a 3x3 matrix
try:
    matrix_3x3 = np.arange(9).reshape(3, 3)  # Sequential array reshaped into 3x3 matrix
    print("3x3 Matrix:\n", matrix_3x3)
except AttributeError as e:
    print("Error: ", e)
    print("Make sure NumPy is installed and correctly imported.")






3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#3.	Create a 3X3 identity matrix
#import NumPy
import numpy as np
#create a 3x3 identity matrix
#identify matrix has 1 along the diagnal and 0 elsewhere, created using np.eye()
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#4.	Create a random array of size 30 and find the mean of the array.
#import NumPy
import numpy as np
#generate 30 random numbers between 0 and 1, then calculating their average
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array:\n", random_array)
print("Mean of Random Array:, mean_value")

Random Array:
 [0.77120289 0.55292218 0.7902192  0.6580902  0.7147284  0.36569745
 0.61100084 0.37096434 0.31382765 0.01897936 0.97822839 0.65333975
 0.99293861 0.61678947 0.92297218 0.3183052  0.23263243 0.67981077
 0.31090194 0.13787024 0.87296268 0.30402395 0.31803095 0.1821014
 0.53088736 0.60429654 0.55442624 0.1090643  0.06139113 0.53685946]
Mean of Random Array:, mean_value


In [ ]:
#5.	Create a 10X10 array with random values and find the minimum and maximum values.
#import Numpy
import numpy as np
#np.random.random() generates random numbers; we use min()and max() to find the smallest and largest values
large_random_array = np.random.random((10, 10))
min_value = large_random_array.min()
max_value = large_random_array.max()
print("Random 10x19 Array:\n", large_random_array)
print("Min Value:", min_value)
print("Max Value:", max_value)




Random 10x19 Array:
 [[0.85061958 0.05447069 0.44764355 0.3885423  0.22072929 0.89886772
  0.05675334 0.25590342 0.94836936 0.49825282]
 [0.9105992  0.59733796 0.25543933 0.67807202 0.87622557 0.69277968
  0.30839889 0.04685578 0.7211368  0.78030741]
 [0.61487    0.18990434 0.93729005 0.33037821 0.47060494 0.28687407
  0.80804083 0.79728004 0.21635589 0.1755344 ]
 [0.62040595 0.21256939 0.62136893 0.79151023 0.40605575 0.6092062
  0.58466989 0.79835677 0.41158838 0.77309185]
 [0.02912677 0.84434871 0.60446666 0.14477023 0.01339755 0.21693587
  0.80407362 0.0025983  0.18352112 0.95975961]
 [0.16555652 0.00373831 0.84817544 0.05215344 0.22731671 0.2983134
  0.20251622 0.6253457  0.56305708 0.32838486]
 [0.1297056  0.39113172 0.65659719 0.66807136 0.04689108 0.2719553
  0.87864348 0.07877734 0.02612975 0.1454151 ]
 [0.35508658 0.66662828 0.66102363 0.81558791 0.1666244  0.35242977
  0.50402403 0.12104249 0.6986735  0.72506789]
 [0.39731092 0.22851037 0.84542543 0.14490122 0.91255216 0.854

In [ ]:
#6.	Create a zero array of size 10 and replace 5th element with 1.
#import NumPy
import numpy as np
#create a zero array of size 10 and replace the 5th element with 1
#starting with an all-zero array, then modifying the 5th position (index4) to store the value 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("Reversed Array:\n", zero_array)

Reversed Array:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7.	Reverse an array arr = [1,2,0,0,4,0].
#import NumPy
import numpy as np
#using slicing[::-1] to flip the order of elements in an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]
print("Reversed Array:\n", reversed_array)


Reversed Array:
 [0 4 0 0 2 1]


In [ ]:
#8.Create a 2D array with 1 on the border and 0 inside
#import NumPy
import numpy as np
#start with an all-ones array, then overwrite the "inside" region with zeros
bordered_array = np.ones((5, 5))
bordered_array[1:-1, 1:-1] = 0 #Target the inner portion of the 2D array
print("Bordered Array:\n", bordered_array)


Bordered Array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#9.	Create a 8X8 matrix and fill it with a checkerboard pattern.
#import NumPy
import numpy as np
# Filling alternate positions with 1s to mimic a chess/checkerboard layout
checkerboard = np.zeros((8, 8), dtype=int)  # Initialize with zeros
checkerboard[1::2, ::2] = 1  # Fill rows starting from the 2nd with alternating 1s
checkerboard[::2, 1::2] = 1  # Fill rows starting from the 1st with alternating 1s
print("Checkerboard Pattern:\n", checkerboard)



Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#Array Operations

In [ ]:
from os import waitid_result
#Arrays for operation
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
#import NumPy as the np
import numpy as np
#1. Add two arrays
sum_arrays = np.add(x, y)
print("Sum of Arrays:\n", sum_arrays)

#2. Subtract two arrays
diff_arrays = np.subtract(x, y)
print("\nDifference of Arrays:\n", diff_arrays)

#3. Multiply array with an integer
scaled_array = x * 6
print("\nScaled Array:\n", scaled_array)

#4. Square each element
squared_array = np.square(x)
print("\nSquared Array:\n", squared_array)

#5. Dot product between various arrays
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot Product (v.w):\n", dot_vw)
print("\nDot Product (x.v):\n", dot_xv)
print("\nDot Product (x.y):\n", dot_xy)

#6. Concatenate x and y along rows; v and w along columns
concat_xy_rows = np.concatenate((x, y), axis=0)
concat_vw_cols = np.column_stack((v, w))
print("\nConcatenated x and y along rows:\n", concat_xy_rows)
print("\nConcatenated v and w along columns:\n", concat_vw_cols)

#7. Concatenate x and v; explain error
try:
  concat_xv = np.concatenate((x, v), axis=0)
  print("Concatenated x and v:\n", concat_xv)
except ValueError as e:
  print("\nError:", e)
  print("\nExplanation: Arrays x and v have incompatible shapes for concatenation")


Sum of Arrays:
 [[ 6  8]
 [10 13]]

Difference of Arrays:
 [[-4 -4]
 [-4 -3]]

Scaled Array:
 [[ 6 12]
 [18 30]]

Squared Array:
 [[ 1  4]
 [ 9 25]]

Dot Product (v.w):
 219

Dot Product (x.v):
 [29 77]

Dot Product (x.y):
 [[19 22]
 [50 58]]

Concatenated x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenated v and w along columns:
 [[ 9 11]
 [10 12]]

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation: Arrays x and v have incompatible shapes for concatenation


In [ ]:
#Matrix Operations

In [ ]:
import numpy as np
#Matrices for operations
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

#1. Prove A.A^-1 = I
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("A * A^-1:\n", identity)

#2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nA * B:\n", AB)
print("\nB * A:\n", BA)
print("AB equals BA:", np.array_equal(AB, BA))

#3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("\n(AB)^T:\n", AB_T)
print("\nB^T * A^T:\n", BT_AT)





#solve system of linear equations
#represent equations in matrix form: AX = B
coefficients = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
constants = np.array([-1, -3, 9])
solution = np.linalg.solve(coefficients, constants)
print("\nSolution to linear equations:\n", solution)

A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

A * B:
 [[23 13]
 [51 29]]

B * A:
 [[36 44]
 [13 16]]
AB equals BA: False

(AB)^T:
 [[23 51]
 [13 29]]

B^T * A^T:
 [[23 51]
 [13 29]]

Solution to linear equations:
 [ 2.  1. -2.]
